const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const build=fs.readFileSync(path.join(root,'build.py'),'utf8');
const release=fs.readFileSync(path.join(root,'src/release.js'),'utf8');
const template=fs.readFileSync(path.join(root,'index.template.html'),'utf8');
const v015=fs.readFileSync(path.join(root,'src/v015polish.js'),'utf8');
const v016=fs.readFileSync(path.join(root,'src/v016polish.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
assert(build.includes("VERSION='0.16'"),'build version must be v0.16');
assert(build.includes("Neon-Descent-v{VERSION}.html"),'build must emit a versioned standalone filename');
assert(build.includes("'v015polish'"),'build must retain the v0.15 Mag-Cable polish layer');
assert(build.includes("'v016polish'"),'build must bundle the v0.16 grip/pause polish layer');
assert(release.includes("const VERSION='__NEON_VERSION__'"),'release HUD/title must use the build-injected version');
assert(template.includes('/*V014PRE*/'),'standalone template must retain v0.14 camera migration before options polish');
assert(template.includes('/*V013POLISH*/'),'standalone template must retain v0.13 field polish layer');
assert(template.includes('/*V014POLISH*/'),'standalone template must retain v0.14 field polish layer');
assert(template.includes('/*V015POLISH*/'),'standalone template must retain v0.15 Mag-Cable polish layer');
assert(template.includes('/*V016POLISH*/'),'standalone template must load v0.16 grip/pause polish layer');
assert(template.includes('/*RELEASE*/'),'standalone template must load release layer');
assert(v015.includes('drawCableClimber'),'v0.15 must keep a cable-specific climb pose');
assert(v016.includes('drawGripClinger'),'v0.16 must keep a Magnetic Grip-specific wall pose');
assert.equal(pkg.version,'0.16.0','package version should match v0.16 release');
console.log('PASS v0.16 artifact, title version source, cable layer, grip layer, and pause/settings layer are synchronized');
