const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const context={window:{},console,Math,Set,Uint8Array};
context.UI={close(){},end(){},pause(){}};
context.Input={state:{},edges:{},reset(){this.state={};this.edges={}},down(a){return !!this.state[a]},axis(){return (+!!this.state.right)-(+!!this.state.left)},pressed(a){return !!this.edges[a]}};
vm.createContext(context);vm.runInContext(fs.readFileSync(root+'/src/core.js','utf8')+'\n'+fs.readFileSync(root+'/src/game.js','utf8'),context);
const N=context.window.ND,G=context.window.Game,I=context.Input,results=[];
const test=(name,fn)=>{try{fn();results.push({name,pass:true});console.log('PASS',name)}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message)}};
function arena(){G.start(77);G.l.tiles.fill(0);G.l.ladders.fill(0);G.l.platforms=[];G.l.traps=[];G.l.shops=[];G.l.doors=[];G.l.cables=[];G.entities=[];G.shots=[];for(let x=0;x<42;x++){G.l.tiles[20*42+x]=1;G.l.tiles[33*42+x]=6;}Object.assign(G.p,{x:400,y:640-.001,ground:true,vy:0,vx:0,fallStart:640,inv:0,hp:8,cool:0});I.reset();return G.p;}
function step(frames,state={}){I.state=state;for(let i=0;i<frames;i++){G.step(1/60);I.edges={}}}
function equip(id){G.equip(G.spawn({kind:'item',id,x:G.p.x,y:G.p.y}));}
test('1,024 seeded stages validate before and after optional rooms',()=>{let repairs=0;for(let s=1;s<=256;s++)for(let stage=1;stage<=4;stage++){let l=N.generate(s*7919,stage);assert(l.initialValidation.ok);assert(l.validation.ok);assert(l.validation.frames>0);repairs+=l.repairs;}results.push({metric:'generatorRepairs',value:repairs});});
test('Seed repeats the same terrain, room templates, loot and exit',()=>{const a=N.generate(87336,3),b=N.generate(87336,3);assert.deepEqual(a.tiles,b.tiles);assert.equal(JSON.stringify(a.spawns),JSON.stringify(b.spawns));assert.equal(JSON.stringify(a.rooms),JSON.stringify(b.rooms));});
test('Generator produces visibly distinct maps',()=>{const keys=new Set();for(let s=1;s<=40;s++)keys.add(Buffer.from(N.generate(s).tiles).toString('base64'));assert.equal(keys.size,40);});
test('Jump height changes with boots; tap jump is shorter',()=>{
  function height(boots,hold){const p=arena();if(boots)equip('jump');I.edges.jump=true;let top=p.y;for(let i=0;i<75;i++){step(1,i<hold?{jump:true}:{});top=Math.min(top,p.y);}return 640-top;}
  const normal=height(false,75),boost=height(true,75),tap=height(false,3);assert(normal>60&&normal<78);assert(boost>normal*1.7);assert(tap<normal*.8);
});
test('Coyote jump and grounded movement brake responsively',()=>{let p=arena();step(30,{right:true});assert(p.x>460);step(12);assert.equal(p.vx,0);});
test('Bomb consumes a charge and destroys actual terrain',()=>{let p=arena();G.bomb(true);assert.equal(p.bombs,3);p.x=650;step(160);assert.equal(N.tileAt(G.l,13,20),0);});
test('Explosion damage, crate impulse and reactor chain reaction',()=>{arena();const e=G.spawn({kind:'enemy',type:'enforcer',x:510,y:640});const c=G.spawn({kind:'item',id:'blade',x:520,y:640});N.setTile(G.l,16,19,4);G.explode(505,620,90);assert(e.dead);assert(c.vy<0);assert(G.entities.some(e=>e.kind==='bomb'&&e.fuse<=.12));step(15);assert.equal(N.tileAt(G.l,16,19),0);});
test('Steel needs two normal hits; boundaries and barriers resist blasts',()=>{arena();N.setTile(G.l,12,18,2);assert.equal(G.breakTile(12,18,1),false);assert.equal(G.breakTile(12,18,1),true);N.setTile(G.l,12,18,6);assert.equal(G.breakTile(12,18,5),false);N.setTile(G.l,12,18,8);assert.equal(G.breakTile(12,18,5),false);});
test('Mag cable consumes one cable and supports climbing',()=>{const p=arena();G.cable();assert.equal(p.cables,3);assert.equal(G.l.cables.length,1);step(45,{up:true});assert(p.y<575);assert(p.climb);});
test('Grip gloves allow wall climbing',()=>{const p=arena();equip('grip');for(let y=12;y<20;y++)N.setTile(G.l,13,y,1);p.x=13*32-p.w/2-1;p.face=1;step(45,{up:true,right:true});assert(p.y<570);});
test('Traction boots prevent electric floor damage',()=>{const p=arena();G.l.traps=[{type:'electric',x:p.x,y:p.y,phase:0,cool:0}];equip('traction');step(30);assert.equal(p.hp,8);p.passives.delete('traction');step(35);assert(p.hp<8);});
test('Adhesive charge attaches on contact',()=>{const p=arena();equip('adhesive');G.bomb(true);step(45);const b=G.entities.find(e=>e.kind==='bomb');assert(b&&b.static);});
test('Glide, jet and hover affect flight; backpacks swap',()=>{for(const id of ['glide','jet','hover']){const p=arena();equip(id);p.y=420;p.fallStart=420;p.ground=false;p.vy=200;step(45,{jump:true});assert(id==='jet'?p.y<420:p.y<505);if(id!=='glide')assert(p.fuel<1);equip('core');assert.equal(p.back,'core');assert(G.entities.some(e=>!e.dead&&e.id===id));}});
test('Emergency decelerator triggers once and reduces a dangerous fall',()=>{const p=arena();equip('decel');p.y=150;p.fallStart=150;p.ground=false;step(70);assert(!p.passives.has('decel'));assert(p.vy<=75);assert.equal(p.hp,8);});
test('Fall damage and death end a run; restart clears state',()=>{const p=arena();p.y=100;p.fallStart=100;p.ground=false;p.hp=3;step(100);assert.equal(G.mode,'dead');G.start(81);assert.equal(G.mode,'play');assert.equal(G.p.hp,5);assert(!G.p.dead);assert.equal(G.p.bombs,4);});
test('Power core increases melee and plasma blast reach',()=>{let p=arena();equip('core');const e=G.spawn({kind:'enemy',type:'enforcer',x:p.x+30,y:p.y,dir:1});G.attack();assert.equal(e.hp,4);});
test('Shotgun fires spread; all ranged weapons spend ammo and damage',()=>{for(const id of ['shotgun','cryo','bolt','foam']){let p=arena();equip(id);const e=G.spawn({kind:'enemy',type:'enforcer',x:p.x+100,y:p.y,dir:1});const ammo=p.ammo;G.attack();assert.equal(p.ammo,ammo-1);assert.equal(G.shots.length,id==='shotgun'?5:1);step(12);assert(e.hp<6||e.dead);if(id==='cryo')assert(e.freeze>0);if(id==='foam')assert(e.foam>0);}});
test('Frozen targets shatter when struck again',()=>{arena();const e=G.spawn({kind:'enemy',type:'enforcer',x:450,y:640,freeze:2});G.damage(e,1,400,640,'player');assert(e.hp<=1);});
test('Bolt sticks into wall and can be recovered',()=>{let p=arena();equip('bolt');for(let y=17;y<20;y++)N.setTile(G.l,16,y,1);G.attack();step(25);const b=G.entities.find(e=>e.kind==='boltPickup');assert(b);p.x=b.x;p.y=b.y;const ammo=p.ammo;step(1);assert.equal(p.ammo,ammo+1);});
test('Phase teleporter skips a wall but never places player inside it',()=>{let p=arena();equip('phase');for(let y=16;y<20;y++)N.setTile(G.l,14,y,1);G.attack();assert(p.x>=500);assert(!N.blocked(G.l,p.x,p.y,p.w,p.h));});
test('Plasma cutter removes tiles and spends durability',()=>{let p=arena();equip('cutter');N.setTile(G.l,13,19,1);G.attack();assert.equal(N.tileAt(G.l,13,19),0);assert.equal(p.ammo,34);});
test('Disc returns; mono-blade has longer reach and damage',()=>{let p=arena();equip('disc');G.attack();step(100);assert(!G.shots.some(s=>s.type==='disc'));p=arena();equip('blade');const e=G.spawn({kind:'enemy',type:'enforcer',x:p.x+55,y:p.y,dir:1});G.attack();assert.equal(e.hp,3);});
test('Riot barrier blocks incoming front projectile',()=>{const p=arena();equip('shield');G.shots.push({x:p.x+30,y:p.y-15,vx:-400,vy:0,life:1,owner:'enemy',type:'pulse',damage:1,hits:new Set()});step(8);assert.equal(p.hp,8);});
test('Supplies add charges/cables/health; scanners equip',()=>{const p=arena();p.hp=3;for(const id of ['bombs','bombcrate','cables','health','scanner','optics'])equip(id);assert.equal(p.bombs,17);assert.equal(p.cables,7);assert.equal(p.hp,5);assert(p.passives.has('scanner')&&p.passives.has('optics'));});
test('Keys and Master Override unlock optional doors; explosives breach them',()=>{for(const method of ['key','override','bomb']){const p=arena();const d={x:13,y:18,key:'K1',open:false};G.l.doors=[d];N.setTile(G.l,13,18,7);N.setTile(G.l,13,19,7);p.x=410;if(method==='key')p.keys.push('K1');if(method==='override')equip('override');if(method==='bomb')G.explode(430,612,65);else G.interact();assert(d.open);assert.equal(N.tileAt(G.l,13,19),0);if(method==='key')assert.equal(p.keys.length,0);}});
function shop(){let p=arena();G.l.shops=[{id:0,x:350,y:510,w:250,h:130,angry:false}];G.l.exit={x:1200,y:640};let e=G.spawn({kind:'item',id:'jump',x:p.x,y:p.y,shop:0,price:950});return {p,e};}
test('Shop inspection and purchase charge money without hostility',()=>{const {p,e}=shop();p.money=1000;G.interact();assert.equal(p.held,e);G.interact();assert.equal(p.money,50);assert(p.passives.has('jump'));assert(!G.wanted);});
test('Returning inspected stock leaves it for sale',()=>{const {p,e}=shop();G.interact();G.interact(true);assert(!p.held);assert(!e.held);assert.equal(e.shop,0);assert(!G.wanted);});
test('Stealing provokes merchant and wanted status carries to later stages',()=>{const {p,e}=shop();G.interact();G.attack();assert(G.wanted);assert(G.l.shops[0].angry);assert(p.passives.has('jump'));G.stage=2;G.loadStage();assert(G.l.shops.every(s=>s.angry));});
test('Merchant aggressively pursues and fires when angered',()=>{shop();G.anger(0);const e=G.spawn({kind:'enemy',type:'merchant',x:540,y:640,shop:0,cool:0});G.updateEnemy(e,1/60);assert(e.vx<0);assert(G.shots.length===5);});
test('Carrying/throwing a crate damages an enemy and releases loot',()=>{const p=arena();const crate=G.spawn({kind:'crate',x:410,y:640}),enemy=G.spawn({kind:'enemy',type:'crawler',x:480,y:640});G.interact();assert.equal(p.held,crate);G.throwHeld();step(18);assert(enemy.hp<2||enemy.dead);assert(crate.dead);});
test('Mines respond to enemy bodies and chain with bombs',()=>{arena();G.l.traps=[{type:'mine',x:500,y:640,cool:0,phase:0}];G.spawn({kind:'enemy',type:'sentry',x:500,y:640});step(40);assert(G.l.traps[0].dead);});
test('All ten enemy types update safely and can take damage',()=>{arena();for(const type of ['crawler','skitter','burrow','flyer','slug','sentry','enforcer','detonator','phase','mimic'])G.spawn({kind:'enemy',type,x:650+Math.random()*100,y:640});step(240);assert(G.entities.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)));});
test('Null Warden warns before spawning away from the player',()=>{arena();G.time=165.1;step(1);assert(G.warned);G.time=180;step(1);assert(G.warden);assert(N.dist(G.p,G.warden)>200);});
test('Exit interaction advances stages and fourth exit wins',()=>{const p=arena();G.l.exit={x:p.x,y:p.y};G.interact();assert.equal(G.stage,2);G.stage=4;G.l.exit={x:G.p.x,y:G.p.y};G.interact();assert.equal(G.mode,'win');});
test('Pause freezes timers and resumes play',()=>{arena();G.pause();const t=G.time;step(120);assert.equal(G.time,t);G.pause();step(1);assert(G.time>t);});
const failed=results.filter(r=>r.pass===false);fs.writeFileSync(root+'/tests/results.json',JSON.stringify({date:new Date().toISOString(),passed:results.filter(r=>r.pass).length,failed:failed.length,results},null,2));if(failed.length)process.exitCode=1;
